<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto

namespace User\Service\V1\Metadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Google\Type\PhoneNumber::initOnce();
        \GPBMetadata\Google\Type\PostalAddress::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8F\x05\x0A\x0Auser.proto\x12\x0Fuser.service.v1\x1A\x1Egoogle/type/phone_number.proto\x1A google/type/postal_address.proto\x1A\x17validate/validate.proto\"4\x0A\x05Users\x12+\x0A\x05users\x18\x01 \x03(\x0B2\x15.user.service.v1.UserR\x05users\"\xDD\x02\x0A\x04User\x12\x1D\x0A\x0Afirst_name\x18\x01 \x01(\x09R\x09firstName\x12\x1B\x0A\x09last_name\x18\x02 \x01(\x09R\x08lastName\x12#\x0A\x0Demail_address\x18\x03 \x01(\x09R\x0CemailAddress\x12A\x0A\x0Epostal_address\x18\x04 \x01(\x0B2\x1A.google.type.PostalAddressR\x0DpostalAddress\x12;\x0A\x0Cphone_number\x18\x05 \x01(\x0B2\x18.google.type.PhoneNumberR\x0BphoneNumber\x129\x0A\x0Acreated_at\x18\x06 \x01(\x0B2\x1A.google.protobuf.TimestampR\x09createdAt\x129\x0A\x0Aupdated_at\x18\x07 \x01(\x0B2\x1A.google.protobuf.TimestampR\x09updatedAtBwZZgithub.com/mekahell/php-go-serialization/internal/proto/go/user/service/v1;user_service_v1\xE2\x02\x18User\\Service\\V1\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

